import { createHash } from "node:crypto";
import { includedMeshNodes, materialFor, meshFor } from "../static-profile.js";

const digest = (bytes) => `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
const n = (value) => {
  if (!Number.isFinite(value)) throw new Error("FBX export received a non-finite number.");
  return Number(value.toFixed(9)).toString();
};
const q = (value) => JSON.stringify(String(value));
const list = (values) => values.map(n).join(",");

export function encodeAuthoringFBX(packet, { inspection } = {}) {
  const includedNodes = packet.assembly.nodes.filter((node) => node.included),
    meshNodes = includedMeshNodes(packet),
    materials = new Map(),
    ids = assignIds(includedNodes, meshNodes, packet),
    lines = [
      "; FBX 7.4.0 project file",
      "; Generated by NexusEngine Editor Export",
      "FBXHeaderExtension:  {",
      "    FBXHeaderVersion: 1003",
      "    FBXVersion: 7400",
      '    Creator: "NexusEngine Editor FBX provider/1"',
      "}",
      "GlobalSettings:  {",
      "    Version: 1000",
      "    Properties70:  {",
      '        P: "UpAxis", "int", "Integer", "",1',
      '        P: "UpAxisSign", "int", "Integer", "",1',
      '        P: "FrontAxis", "int", "Integer", "",2',
      '        P: "FrontAxisSign", "int", "Integer", "",-1',
      '        P: "CoordAxis", "int", "Integer", "",0',
      '        P: "CoordAxisSign", "int", "Integer", "",1',
      `        P: "UnitScaleFactor", "double", "Number", "",${n((packet.assembly.units?.metersPerUnit ?? 1) * 100)}`,
      '        P: "OriginalUnitScaleFactor", "double", "Number", "",100',
      "    }",
      "}",
    ];
  for (const node of meshNodes) {
    const material = materialFor(packet, node);
    if (material) materials.set(material.id, material);
  }
  lines.push(
    "Definitions:  {",
    "    Version: 100",
    `    Count: ${meshNodes.length + includedNodes.length + materials.size}`,
    '    ObjectType: "Geometry" {',
    `        Count: ${meshNodes.length}`,
    "    }",
    '    ObjectType: "Model" {',
    `        Count: ${includedNodes.length}`,
    "    }",
    '    ObjectType: "Material" {',
    `        Count: ${materials.size}`,
    "    }",
    "}",
    "Objects:  {",
  );
  for (const node of meshNodes) {
    const mesh = meshFor(packet, node),
      geometryId = ids.geometry.get(node.id),
      modelId = ids.model.get(node.id),
      vertices = mesh.positions,
      polygons = polygonVertexIndices(mesh.indices),
      polygonNormals = mesh.indices.flatMap((index) => mesh.normals.slice(index * 3, index * 3 + 3)),
      polygonUVs = mesh.indices.flatMap((index) => (mesh.uvs ?? []).slice(index * 2, index * 2 + 2));
    lines.push(
      `    Geometry: ${geometryId}, ${q(`Geometry::${node.id}`)}, "Mesh" {`,
      "        GeometryVersion: 124",
      `        Vertices: *${vertices.length} {`,
      `            a: ${list(vertices)}`,
      "        }",
      `        PolygonVertexIndex: *${polygons.length} {`,
      `            a: ${polygons.join(",")}`,
      "        }",
      "        LayerElementNormal: 0 {",
      "            Version: 101",
      '            Name: ""',
      '            MappingInformationType: "ByPolygonVertex"',
      '            ReferenceInformationType: "Direct"',
      `            Normals: *${polygonNormals.length} {`,
      `                a: ${list(polygonNormals)}`,
      "            }",
      "        }",
    );
    if (polygonUVs.length) {
      lines.push(
        "        LayerElementUV: 0 {",
        "            Version: 101",
        '            Name: "UVChannel_1"',
        '            MappingInformationType: "ByPolygonVertex"',
        '            ReferenceInformationType: "Direct"',
        `            UV: *${polygonUVs.length} {`,
        `                a: ${list(polygonUVs)}`,
        "            }",
        "        }",
      );
    }
    lines.push(
      "        Layer: 0 {",
      "            Version: 100",
      '            LayerElement:  { Type: "LayerElementNormal" TypedIndex: 0 }',
      ...(polygonUVs.length
        ? ['            LayerElement:  { Type: "LayerElementUV" TypedIndex: 0 }']
        : []),
      "        }",
      "    }",
    );
    const [rx, ry, rz] = quaternionToEulerDegrees(node.transform.rotation);
    lines.push(
      `    Model: ${modelId}, ${q(`Model::${node.id}`)}, "Mesh" {`,
      "        Version: 232",
      "        Properties70:  {",
      `            P: "Lcl Translation", "Lcl Translation", "", "A",${list(node.transform.translation)}`,
      `            P: "Lcl Rotation", "Lcl Rotation", "", "A",${list([rx, ry, rz])}`,
      `            P: "Lcl Scaling", "Lcl Scaling", "", "A",${list(node.transform.scale)}`,
      "        }",
      "        Shading: T",
      '        Culling: "CullingOff"',
      "    }",
    );
  }
  for (const node of includedNodes.filter((entry) => !entry.meshId)) {
    const modelId = ids.model.get(node.id),
      [rx, ry, rz] = quaternionToEulerDegrees(node.transform.rotation);
    lines.push(
      `    Model: ${modelId}, ${q(`Model::${node.id}`)}, "Null" {`,
      "        Version: 232",
      "        Properties70:  {",
      `            P: "Lcl Translation", "Lcl Translation", "", "A",${list(node.transform.translation)}`,
      `            P: "Lcl Rotation", "Lcl Rotation", "", "A",${list([rx, ry, rz])}`,
      `            P: "Lcl Scaling", "Lcl Scaling", "", "A",${list(node.transform.scale)}`,
      "        }",
      "        Shading: T",
      '        Culling: "CullingOff"',
      "    }",
    );
  }
  for (const material of materials.values()) {
    const id = ids.material.get(material.id),
      p = material.pbr,
      transparency = 1 - p.baseColor[3],
      shininess = Math.max(0, Math.min(100, (1 - p.roughness) * 100));
    lines.push(
      `    Material: ${id}, ${q(`Material::${material.id}`)}, "" {`,
      "        Version: 102",
      '        ShadingModel: "phong"',
      "        MultiLayer: 0",
      "        Properties70:  {",
      `            P: "DiffuseColor", "Color", "", "A",${list(p.baseColor.slice(0, 3))}`,
      '            P: "DiffuseFactor", "Number", "", "A",1',
      `            P: "EmissiveColor", "Color", "", "A",${list(p.emissive)}`,
      `            P: "ReflectionFactor", "Number", "", "A",${n(p.metallic)}`,
      `            P: "Shininess", "double", "Number", "",${n(shininess)}`,
      `            P: "TransparencyFactor", "Number", "", "A",${n(transparency)}`,
      "        }",
      "    }",
    );
  }
  lines.push("}", "Connections:  {");
  for (const node of includedNodes) {
    const modelId = ids.model.get(node.id),
      parent = node.parent && ids.model.has(node.parent) ? ids.model.get(node.parent) : 0,
      material = node.meshId ? materialFor(packet, node) : null;
    if (node.meshId) lines.push(`    C: "OO",${ids.geometry.get(node.id)},${modelId}`);
    lines.push(`    C: "OO",${modelId},${parent}`);
    if (material) lines.push(`    C: "OO",${ids.material.get(material.id)},${modelId}`);
  }
  lines.push("}", "");
  const bytes = Buffer.from(lines.join("\n"), "utf8"),
    hash = digest(bytes);
  return {
    bytes,
    hash,
    fileName: "scene.fbx",
    auxiliaryFiles: [],
    provenance: {
      schema: "nexusengine.editor-export/1",
      format: "fbx",
      adapter: "native-fbx-ascii-static/1",
      profile: "fbx-ascii-7.4-static/1",
      sourcePacket: packet.hash,
      source: packet.source,
      outputHash: hash,
      byteLength: bytes.length,
      warnings: [
        ...(packet.warnings ?? []),
        ...(inspection?.issues ?? []).filter((issue) => issue.severity === "warning"),
      ],
    },
  };
}

function assignIds(nodes, meshNodes, packet) {
  let next = 100000;
  const geometry = new Map(),
    model = new Map(),
    material = new Map();
  for (const node of meshNodes) geometry.set(node.id, next++);
  for (const node of nodes) model.set(node.id, next++);
  for (const item of packet.materials ?? []) material.set(item.id, next++);
  return { geometry, model, material };
}

function polygonVertexIndices(indices) {
  const result = [];
  for (let i = 0; i < indices.length; i += 3)
    result.push(indices[i], indices[i + 1], -indices[i + 2] - 1);
  return result;
}

function quaternionToEulerDegrees([x, y, z, w]) {
  const sinrCosp = 2 * (w * x + y * z),
    cosrCosp = 1 - 2 * (x * x + y * y),
    roll = Math.atan2(sinrCosp, cosrCosp),
    sinp = 2 * (w * y - z * x),
    pitch = Math.abs(sinp) >= 1 ? Math.sign(sinp) * Math.PI / 2 : Math.asin(sinp),
    sinyCosp = 2 * (w * z + x * y),
    cosyCosp = 1 - 2 * (y * y + z * z),
    yaw = Math.atan2(sinyCosp, cosyCosp),
    d = 180 / Math.PI;
  return [roll * d, pitch * d, yaw * d];
}
